version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"                         # AWS Region
    AWS_ACCOUNT_ID: "905418229977"                  # Your AWS account ID
    REPO_NAME: "ecs-fargate-app"                    # ECR Repo Name
    ecs_container_name: "web-app-container"         # ECS Container Name

phases:
  pre_build:
    commands:
      - echo "Starting pre-build stage..."
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Pre-build stage completed."

  build:
    commands:
      - echo "Starting build stage..."
      - echo "Building the Docker image..."
      # Use a valid Docker tag format, using the first 7 characters of the commit hash for IMAGE_TAG
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo "Build stage completed."

  post_build:
    commands:
      - echo "Starting post-build stage..."
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $ecs_container_name $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Post-build stage completed."

artifacts:
  files:
    - imagedefinitions.json
