version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "905418229977"
    REPO_NAME: "ecs-fargate-app"
    IMAGE_TAG: "latest"
    ECS_CONTAINER_NAME: "web-app-container"

phases:
  pre_build:
    commands:
      - echo "Starting pre-build stage..."
      - echo "Logging in to Docker Hub..."
      - docker login -u mark235 -p dckr_pat_BLGX_Mo4j1b_XbCc-W8yHMjNkDU
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Pre-build stage completed."

  build:
    commands:
      - echo "Starting build stage..."
      - echo "Building the Docker image..."
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG .
      - echo "Build stage completed."

  post_build:
    commands:
      - echo "Starting post-build stage..."
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG > /codebuild/output/imagedefinitions.json
      - echo "Post-build stage completed."

artifacts:
  files:
    - /codebuild/output/imagedefinitions.json
